### ISSUE TITLE
pubspec.yaml marked with errors

### ISSUE THREAD

**Issue by vogella** [eclipse/dartboard#145]
I'm following https://www.vogella.com/tutorials/Dart/article.html#exercise-developing-server-and-frontend and created the follwoing pubspec.yaml .

````
name: server
description: A Dart server app

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  json_annotation: ^2.0.0 

dev_dependencies:
  # Your other dev_dependencies here
  build_runner: ^1.0.0
  json_serializable: ^2.0.0 
````

The file shows errors, maybe an error in WWD? If yes, please follow up with upstream.

![image](https://user-images.githubusercontent.com/139910/64535037-dbb00d00-d316-11e9-9652-72525a39754b.png)
